#!/bin/sh
### new
alias si="sxiv"
alias pa="pass"
alias we="weechat"
#alias tm="tmux"
#### systemctl func
systemctl_toggle_service()
{
    local service="${1}"
    if [ -n "${2}" ]; then
        local user_hand="--user"
    fi

    if systemctl ${user_hand} is-active --quiet "${service}"; then
        systemctl ${user_hand} stop "${service}"
        echo "stopped ${service}"
    else
        systemctl ${user_hand} start "${service}"
        echo "started ${service}"
    fi
}
systemctl_toggle_service_user()
{
    [ -n ${1} ] || { echo "no input"; return }
    systemctl_toggle_service ${1} user
}

### dotfiles
alias irssi="irssi --home=${XDG_CONFIG_HOME}/irssi"
alias abook="abook \
    --config ${XDG_CONFIG_HOME}/abook/abookrc \
    --datafile ${XDG_DATA_HOME}/abook/addressbook"
alias tmux="tmux -f ${XDG_CONFIG_HOME}/tmux/tmux.conf"
alias nrss="nrss -D ${XDG_CONFIG_HOME}/nrss/ \
    -F ${XDG_CACHE_HOME}/nrss/feeds \
    -L ${XDG_CACHE_HOME}/nrss/log"
alias esniper="esniper -c ${XDG_CONFIG_HOME}/esniper/conf"
alias apvlv="apvlv -c ${XDG_CONFIG_HOME}/apvlv/apvlvrc"
alias mbsync="mbsync -c ${XDG_CONFIG_HOME}/isync/isyncrc"
alias mr="mr --config ${HOME}/.config/mr/mrconfig"
alias castget="castget -C ${HOME}/.config/castget/castgetrc"
alias mpv="mpv --config-dir=${HOME}/.config/mpx"
#alias xrdbx="xrdb -I${HOME} -merge ${XDG_CONFIG_HOME}/X11/xresources"
alias xrdbx="xrdb -I${XDG_CONFIG_HOME} -merge ${XDG_CONFIG_HOME}/X11/xresources"
alias ref="shortcuts >/dev/null; \
    source ${XDG_CONFIG_HOME:-${HOME}/.config}/shortcutrc ; \
    source ${XDG_CONFIG_HOME:-${HOME}/.config}/zshnameddirrc"
### gen
alias tabbedx="tabbed -r 2 st -w ''"
alias libr="libreoffice"
alias bc="bc -ql"
alias sc="sc-im"
### files
alias c="cd"
alias cc="cd"
alias cp="cp -iv"
alias mv="mv -iv"
alias mkd="mkdir -pv"
alias lns='ln -s'
alias chx="chmod +x"
alias rm="rm -vI"
alias rm='echo "NOTE: use trash-put instead, but if youre sure \
    use /rm to overide"; false'
alias rmm='echo "Using trash-put"; trash-put -v'
alias tp="trash-put"
alias dir="dir --color=auto"
alias vdir="vdir --color=auto"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias ls="ls --color=auto"
alias l="ls"
alias lsl='ls -l --group-directories-first'
alias lsa='ls -lA --group-directories-first'
alias lsb='ls -A'
alias g="git"
alias mrstatus="cd /dat && mr status | less"
alias si='sxiv' #alias sx='sxiv'
alias r='ranger'
alias nnn="nnn -a"
alias n="nnn -ea"
alias e="${EDITOR}"
alias v="vi"
alias vc="cud && nvim -c Ntr"
alias vimdiff="nvim -d"
alias openu="xdg-open "${@}" &"
alias open='openu'
alias o='openu' #alias op='
# media
alias yt="yt-dlp --add-metadata"
alias ytx="yt -x"
alias yt4="yt -f 'bestvideo[height<=480]+bestaudio/best[height<=480]'"
alias yt7="yt -f 'bestvideo[height<=720]+bestaudio/best[height<=720]'"
alias yt-cook="yt --cookies-from-browser firefox -o '%(id)s.%(ext)s'"
alias ffmpeg="ffmpeg -hide_banner" # ffmpeg
alias mpd-reset="systemctl --user stop mpd.service"
alias a="vimpc"
#alias ytv="youtube-viewer"
#### systemctl user
alias smu="systemctl --user"
alias red="systemctl_toggle_service_user redshift.service"
alias qbd="systemctl_toggle_service_user qb.service"
alias chromed="systemctl_toggle_service_user chrome.service"
#### systemctl system
alias sm="systemctl"
alias reboot="systemctl reboot"
alias sms="systemctl suspend"
alias nm-restart="systemctl restart NetworkManager.service"
alias blue="systemctl_toggle_service bluetooth.service"
alias jelly="systemctl_toggle_service jellyfin.service"
alias jelly-nft-flush="sudo nft flush ruleset"
alias paperless="systemctl_toggle_service paperless.target"
alias clamd-sys="systemctl_toogle_service clamav-daemon.service"
#alias sdk-clamd='sudo pkill clamd'
    # convert to systemctl switch
#### system
alias shutdownx="shutdown -h now"
alias unmountall='udiskie-umount -a --detach'
alias feh-setbg='feh --no-fehbg --bg-fill "${BGX_FEH}"'
alias aut="autorandr --load"
alias autor-a="autorandr --load dock-ad"
alias jxe='journalctl -xe'
alias xi="exec xini"
#[ -f "${XINITRC}" ] && alias startx="startx ${XINITRC}"
for x in mount umount sv pacman updatedb su dmesg shutdown; do
    alias ${x}="sudo ${x}"
done
alias so="sudo"
alias sdk="sudo pkill"
#killc() { i=0; while i < 10 ; do sudo pkill ${1}; done } # aggressive kill
alias p="pacman"
alias pacs='pacman -S'
alias pipu='pip install --user'
alias ma="make"
#### networking
alias blue-adisconnect="bluetoothctl disconnect"
alias s="ssh"
alias mosh="mosh --experimental-remote-ip=remote"
# other
alias z="zathura"
alias zi="i3-swallow zathura"
alias mn="man"
alias cl="clear"
alias q='exit'
alias magit="nvim -c MagitOnly"
#### tor;mail;news;act
alias tran="transmission-daemon"
alias tranq="transmission-remote --exit"
alias tranr="transmission-remote"
alias tranc="transmission-cli"
#alias m="neomutt -e \"push '<change-folder>=ii<enter>'\""
alias m="neomutt -e 'push <change-folder>=ii<enter>'"
alias nmm="notmuch"
alias mbsync-pull-new-mailboxs="mbsync --pull --create -a"
alias news="newsboat"
alias ne="newsboat"
alias hl='hledger'
alias hla='hledger add'
#### task
alias tt='taskwarrior-tui'
alias j='task'
alias jj='task'
alias vit="TASKRC_ORIG=${TASKRC}; TASKRC=${VITRC}; /usr/bin/vit; TASKRC=${TASKRC_ORIG}"
#### webapps
alias wa='qb win web.whatsapp.com'
alias gpt='qb win chat.openai.com'
alias gpt-chrome='google-chrome-stable --app=https://chatgpt.com/'
alias calx='qb win calendar.google.com'
alias habit='qb w.oo.win'
alias b="buku --suggest"
#### new
alias brw-inx="qb"
#alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'
#alias whatsapp='firefox --new-window web.whatsapp.com'
#export mpvx="mpx"
#alias weechat="weechat -d ${XDG_CONFIG_HOME}/weechat/" # weechat now abides by default
#archive
#alias red-start="systemctl --user start redshift.service"
#alias red-stop="systemctl --user stop redshift.service"
#alias feh-setbg='feh --no-fehbg --bg-max "${BGX_FEH}"'
#alias blue='bluetuith'
#alias blue-stop="systemctl stop bluetooth.service"
#alias xini="xini"
#alias srcp="source ~/.config/shell/profile"
#alias dmu_j4x="j4-dmenu-desktop --dmenu 'dmenu \
#    -b \
#    -nb \"black\" \
#    -nf \"#efef8f\" \
#    -sb \"black\" \
#    -sf \"white\"'"
