#!/bin/sh
### new
### gen
alias tabbedx="tabbed -r 2 st -w ''"
alias mr="mr --config ${HOME}/.config/mr/mrconfig"
alias libr="libreoffice"
alias bc="bc -ql"
alias sc="sc-im"
### files
alias cc="cd"
alias cp="cp -iv"
alias mv="mv -iv"
alias mkd="mkdir -pv"
alias lns='ln -s'
alias chx="chmod +x"
alias rm="rm -vI"
alias rm='echo "NOTE: use trash-put instead, but if youre sure \
    use /rm to overide"; false'
alias rmm='echo "Using trash-put"; trash-put -v'
alias tp="trash-put"
### ls list
alias dir="dir --color=auto"
alias vdir="vdir --color=auto"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias ls="ls --color=auto"
alias lsl='ls -l --group-directories-first'
alias lsa='ls -lA --group-directories-first'
alias lsb='ls -A'
### nnn;nvim;editor
alias g="git"
alias si='sxiv' #alias sx='sxiv'
alias l='lf'
alias r='ranger'
alias nnn="nnn -a"
alias n="nnn -ea"
alias e="${EDITOR}"
alias v="${EDITOR}"
alias vc="cud && nvim -c Ntr"
alias vimdiff="nvim -d"
alias openu="xdg-open "${@}" &"
alias open='openu'
alias o='openu' #alias op='
# media
alias yt="yt-dlp --add-metadata"
alias ytx="yt -x"
alias ytdlp="yt"
alias yt480="yt -f 'bestvideo[height<=480]+bestaudio/best[height<=480]'"
alias yt-cook="yt --cookies-from-browser firefox -o '%(id)s.%(ext)s'"
alias ytv="youtube-viewer"
alias ffmpeg="ffmpeg -hide_banner" # ffmpeg
alias mpv="mpv --config-dir=${HOME}/.config/mpx"
alias castget="castget -C ${HOME}/.config/castget/castgetrc"
alias mpd-reset="systemctl --user stop mpd.service"
alias a="vimpc"
#### networking
alias blue-adisconnect="bluetoothctl disconnect"
alias blue='bluetuith'
alias s="ssh"
alias mosh="mosh --experimental-remote-ip=remote"
#### system
alias reboot="systemctl reboot"
alias sll="systemctl suspend"
alias shutdownx="shutdown -h now"
alias unmountall='udiskie-umount -a --detach'
alias red-start="systemctl --user start redshift.service"
alias red-stop="systemctl --user stop redshift.service"
alias feh-setbg='feh --no-fehbg --bg-max "${BGX_FEH}"'
alias xrdbx="xrdb -I${HOME} -merge ${XDG_CONFIG_HOME}/X11/xresources"
#alias xrdb-source="xrdb -I${XDG_CONFIG_HOME:-$HOME} .config/X11/xresources"
alias autor-a="autorandr --load dock-ad"
alias jxe='journalctl -xe'
[ -f "${XINITRC}" ] && alias startx="startx ${XINITRC}"
for x in mount umount sv pacman updatedb su dmesg shutdown; do
    alias ${x}="sudo ${x}"
done
alias so="sudo"
alias sdk='sudo pkill'
alias sdk-clamd='sudo pkill clamd'
killc()      { i=0; while i < 10 ; do sudo pkill ${1}; done } # aggressive kill
# other
alias z="zathura"
alias zi="i3-swallow zathura"
alias mn="man"
alias cl="clear"
alias q='exit'
alias magit="nvim -c MagitOnly"
alias ref="shortcuts >/dev/null; \
    source ${XDG_CONFIG_HOME:-${HOME}/.config}/shortcutrc ; \
    source ${XDG_CONFIG_HOME:-${HOME}/.config}/zshnameddirrc"
## packages/pacman/pip
alias p="pacman"
alias pacs='pacman -S'
alias pipu='pip install --user'
alias srcp="source ~/.config/shell/profile"
alias syt='systemctl'
#### dotfiles
alias abook="abook \
    --config ${XDG_CONFIG_HOME}/abook/abookrc \
    --datafile ${XDG_DATA_HOME}/abook/addressbook"
alias weechat="weechat -d ${XDG_CONFIG_HOME}/weechat/"
alias tmux="tmux -f ${XDG_CONFIG_HOME}/tmux/tmux.conf"
alias nrss="nrss -D ${XDG_CONFIG_HOME}/nrss/ \
    -F ${XDG_CACHE_HOME}/nrss/feeds \
    -L ${XDG_CACHE_HOME}/nrss/log"
alias esniper="esniper -c ${XDG_CONFIG_HOME}/esniper/conf"
alias apvlv="apvlv -c ${XDG_CONFIG_HOME}/apvlv/apvlvrc"
alias mbsync="mbsync -c ${XDG_CONFIG_HOME}/isync/isyncrc"
#### transmission remotes
alias tnr="transmission-remote"
alias tnc="transmission-cli"
alias tnd="transmission-daemon"
### mail
alias m="neomutt -e "push '<change-folder>=ii<enter>'""
alias nmm="notmuch"
alias mbsync-pull-create-mailbox="mbsync --pull --create -a"
#### news
alias news="newsboat"
alias ne="newsboat"
#### webapps
#alias whatsapp='qb win web.whatsapp.com'
alias whatsapp='firefox --new-window web.whatsapp.com'
alias wa='whatsapp'
alias gpt='qb win chat.openai.com'
alias calendar='qb win calendar.google.com'
alias cala='calendar'
alias habit='qb w.oo.win'
alias b="buku --suggest"
#alias sw='surfraw'
#alias sf='surfraw -browser="qb"'
#### hleder
alias hl='hledger'
alias hla='hledger add'
#alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'
alias mrstatus="cd /dat && mr status | less"
