#!/bin/sh
# universal interactive shell
# relating solely to interactive shells

## - [ ] add git opts to zsh?
export GIT_PS1_SHOWDIRTYSTATE="1"        # + for staged, * if unstaged.
export GIT_PS1_SHOWSTASHSTATE="1"
export GIT_PS1_SHOWUNTRACKEDFILES="1"    # % if untracked files.
export GIT_PS1_SHOWUPSTREAM="1"          # <, >, <> behind, ahead, diverged from upstream
export GIT_PS1_STATESEPARATOR="1"        # sep between branch name and state symbols
export GIT_PS1_DESCRIBE_STYLE="1"        # show commit relative to tag/branch, detached HEAD
export GIT_PS1_SHOWCOLORHINTS="1"        # display in color

export PIXELFONTSIZE=18 # font

if [ ! -n $(which tput | grep "not found") ]
then
    export BLACK="$(tput setaf 0)"
    export RED="$(tput setaf 1)"
    export GREEN="$(tput setaf 2)"
    export YELLOW="$(tput setaf 3)"
    export LIME_YELLOW="$(tput setaf 190)"
    export POWDER_BLUE="$(tput setaf 153)"
    export BLUE="$(tput setaf 4)"
    export MAGENTA="$(tput setaf 5)"
    export CYAN="$(tput setaf 6)"
    export WHITE="$(tput setaf 7)"
    export BRIGHT="$(tput bold)"
    export NORMAL="$(tput sgr0)"
    export BLINK="$(tput blink)"
    export REVERSE="$(tput smso)"
    export UNDERLINE="$(tput smul)"
fi
