#!/bin/sh
# vim: set ft=sh syntax=sh
export XDG_CACHE_HOME="${HOME}/.cache" 
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share" 
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_BIN_HOME="${HOME}/.local/bin"
export PATH="${XDG_BIN_HOME}:${PATH}"
export XPROFILE="${HOME}/.config/X11/xprofile"
export VISUAL="nvim"
export EDITOR="nvim"
export COLORTERM="truecolor"
export PAGER="less -R --use-color"
export LESSOPEN="|lesspipe.sh %s"; export LESSOPEN
export LESSCOLORIZER='bat'
export MANWIDTH=100
export MANPAGER="less -R --use-color -Dd+r -Du+b"
export MANROFFOPT="-P -c"
export LC_COLLATE="C" # dotfiles first in ls and nnn?
export QT_QPA_PLATFORMTHEME="qt6ct" #export QT_STYLE_OVERRIDE=kvantum
export MAILCAPS=${XDG_CONFIG_HOME}/shell/mailcap
export TERMINAL="st"
export PONYSAY_FULL_WIDTH="y"
export MPD_HOST="127.0.0.1"
export MPD_PORT="6600"
export MPV_SOCKET_DIR="/tmp/mpvsocket."
export MPLAYER_HOME="${XDG_CONFIG_HOME}/mplayer"
export R_ENVIRON=${XDG_CONFIG_HOME}/r/renviron
export R_PROFILE_USER=${XDG_CONFIG_HOME}/r/rprofile
export BLENDER_USER_CONFIG="${XDG_CONFIG_HOME}/blender"
export BLENDER_USER_DATAFILES="${XDG_DATA_HOME}/blender"
export BLENDER_USER_SCRIPTS="${XDG_BIN_HOME}/blender"
export MATES_DIR="${XDG_DATA_HOME}/vdirsyncer/contacts"
export MATES_INDEX="${XDG_DATA_HOME}/mates/mates_index"
# tex
export MANPATH="/usr/local/texlive/2024/texmf-dist/doc/man:${MANPATH}"
export INFOPATH="/usr/local/texlive/2024/texmf-dist/doc/info:${INFOPATH}"
export PATH="/usr/local/texlive/2024/bin/x86_64-linux:${PATH}"
# security
export GPG_TTY=$(tty)
export SSH_AGENT_PID=""
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
#### home cleanup
# cache
export GOMODCACHE="${XDG_CACHE_HOME}/go/mod"
export ICEAUTHORITY="${XDG_CACHE_HOME}/ICEauthority"
export DUC_DATABASE="${XDG_CACHE_HOME}/duc/duc.db"
export GRADLE_USER_HOME="${XDG_CACHE_HOME}/gradle"
export RANDFILE="${XDG_CACHE_HOME}/rnd"
# data
export LESSHISTFILE="${XDG_DATA_HOME}/aax/lesshst"
export HISTFILE="${XDG_DATA_HOME}/aax/history"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export NOTMUCH_DATABASE="$HOME/.local/mail/"
export TASKDATA="${XDG_DATA_HOME}/task"
export TMUX_TMPDIR="${XDG_DATA_HOME}/tmux"
export SSB_HOME="${XDG_DATA_HOME}"/zoom
export PASSWORD_STORE_DIR="${XDG_DATA_HOME}/password-store/"
export MAILDIR="${HOME}/.localx/mail/"
export GNUPGHOME="${XDG_DATA_HOME}"/gnupg
# config
export XINITRC="${XDG_CONFIG_HOME}/X11/xinitrc"
export XSERVERRC="${XDG_CONFIG_HOME}/X11/xserverrc"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export VIMDIR="${XDG_CONFIG_HOME}/nvim"
export MYVIMRC="$VIMDIR/init.lua"
export VIMINIT='let $MYVIMRC="$VIMDIR/init.lua" | source $MYVIMRC'
export TASKRC="${XDG_CONFIG_HOME}/task/taskrc"
export VIT_DIR="${XDG_CONFIG_HOME}/vit"
export TIMEWARRIOR="${XDG_CONFIG_HOME}/timewarrior"
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME}/notmuch/notmuchrc"
export MR_CONFIG="${XDG_CONFIG_HOME}/mr/mrconfig"
# config b
export W3M_DIR="${XDG_CONFIG_HOME}/w3m"
export WWW_HOME="${XDG_CONFIG_HOME}/w3m"
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk2/gtkrc"
export INPUTRC="${XDG_CONFIG_HOME}/inputrc"
export WGETRC="${XDG_CONFIG_HOME}/wgetrc"
export ELINKS_CONFDIR="${XDG_CONFIG_HOME}/elinks"
export WEECHAT_HOME="${XDG_CONFIG_HOME}/weechat"
export NMBGIT="${XDG_CONFIG_HOME}/notmuch/nmbug"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME}/npm/npmrc
export TMSU_DB="${XDG_CONFIG_HOME}/tmsu/defaultdb"
# person
export ZK_NOTEBOOK_DIR="${HOME}/daa/zk"
export BGX_FEH="${XDG_DATA_HOME}/aaa/xbg/bg.png"
export BHQ_DIR="${XDG_CONFIG_HOME}/bhq"
export BHQC="${XDG_CONFIG_HOME}/bhq/bhq"
export BROWSER="/usr/local/bin/qb win"
export SCREENS_DIR="/dat/ui/iis"
#### source
. "${XDG_CONFIG_HOME}/shell/aliases"
. "${XDG_CONFIG_HOME}/shelx/profile"
. "${XDG_CONFIG_HOME}/shell/nnx"
for a in ${XDG_CONFIG_HOME}/shelx/alias*; do . "${a}"; done
[[ -f "~/.config/shelx/envhost-${HOST}" ]] \
    && . "${HOME}/.config/shell_p/envhost-${HOST}"
# new
export DICTIONARY="en_GB"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME}"/java
export SAL_USE_VCLPLUGIN=gtk3
# runtime / system
export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"
export RXVT_SOCKET="${XDG_RUNTIME_DIR}/urxvtd.sock"
#[ "$(tty)" = '/dev/tty1' ] && exec xstart -- -keeptty >${XDG_DATA_HOME}/xorg/zxorg.log 2>&1 # goes last
