return {
    { "rebelot/kanagawa.nvim",         name = 'kanagawa' },
    { "agude/vim-eldar",               name = 'eldar' },
    { 'junegunn/seoul256.vim',         name = 'seoul' },
    { 'jaywilliams/vim-vwilight',      name = 'vwilight' },
    { 'vim-scripts/rastafari.vim',     name = 'rastafari'  },
    { 'lucasprag/simpleblack',         name = 'simpleblack' },
    { 'camgunz/amber',                 name = 'amber' },
    { 'vim-scripts/reloaded.vim',      name = 'reloaded' },
    { 'reedes/vim-thematic',           name = 'thematic' },
    { 'jalvesaq/southernlights',       name = 'southernlights' },
    { 'nanotech/jellybeans.vim',       name = 'jellybeans' },
    { 'NLKNguyen/papercolor-theme',    name = 'papercolor' },
    { 'bluz71/vim-moonfly-colors',     name = 'moonfly' },
    { 'https://github.com/h3xx/vim-late_evening', name = 'late' },
    { 'https://github.com/ray-x/aurora', name = 'aurora' },
    { 'ParamagicDev/vim-medic_chalk',  name = 'medicchalk' },
    { 'tpope/vim-vividchalk',          name = 'vividchalk' },
    { 'rose-pine/neovim',              name = 'rose-pine',
        variant = 'auto',
        disable_background = 'true',},
    { "folke/tokyonight.nvim",
        opts = { style = "moon" },}, -- tokyonight
    { "catppuccin/nvim",
    name = "catppuccin",
    opts = {
      integrations = {
        alpha = true,
        cmp = true,
        gitsigns = true,
        illuminate = true,
        indent_blankline = { enabled = true },
        lsp_trouble = true,
        mini = true,
        native_lsp = {
          enabled = true,
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },},},
        navic = { enabled = true },
        neotest = true,
        noice = true,
        notify = true,
        nvimtree = true,
        semantic_tokens = true,
        telescope = true,
        treesitter = true,
        which_key = true,},},},
}
--{ 'https://github.com/naortega/matrix.vim', name= 'matrix' },
