#!/bin/sh

{
    xset r rate 90 160 &
    xrdb -I${HOME}/.config .config/X11/xresources 2>/dev/null &
    feh --no-fehbg --bg-fill "${BGX_FEH}" &
    autorandr --change
}

if ! $(which systemctl | grep "not found")
then
    systemctl --user import-environment XAUTHORITY DISPLAY GNUPGHOME PATH # How to integrate to systemd?
    
    case ${wm} in
        i3)  systemctl --user start i3.target ;;
        dwm) systemctl --user start dwm.target ;;
        *)   systemctl --user start graphix.target ;;
    esac

else
    slstatus &
    unclutter &
    dunst &
fi
