#!/bin/env bash
# TODO: make case versions: cases of:
# - executes with 'st ...'
# - executes with st and applies a mark
# - executes without st and applies a mark

_sleep="$1"
_class="$2"
_mark="$3"
shift 3
_cmd="$@"

$cmd

i3-msg "mark $_mark"
i3-msg '[class="'"$_class"'" con_mark="'"$_mark"'"] move scratchpad'
i3-msg '[class="'"$_class"'"] move scratchpad'
i3-msg '[class="'"$_class"'"] scratchpad show'

