#!/bin/sh

case ${1} in

    aa)
        echo "mailboxes $(\
            find "$2" \
                -maxdepth 1 -mindepth 1 -type d \
                \( -name "ii.*" \
                    -o -name "j.*" \
                    -o -name "ii" \
                    -o -name "idr" \
                    -o -name "iksp" \
                    -o -name "idr" \) \
                -printf "+'%f' ")"
        ;;
    all)
        echo "mailboxes $(\
            find "$2" \
                -maxdepth 1 -mindepth 1 -type d \
                -printf "+'%f' ")"
        ;;
    nn)
        echo "mailboxes $(\
            find "$2" \
                -maxdepth 1 -mindepth 1 -type d \
                -name "x.*" \
                -printf "+'%f' ")"
        ;;
    tt)
        echo "mailboxes $(\
            find "$2" \
                -maxdepth 1 -mindepth 1 -type d \
                ! -name "x.*" \
                -printf "+'%f' ")"
        ;;
esac
